### ISSUE TITLE
Styling: Fix button inconsistancy

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#288]
Right now there's about 4 or 5 different buttons used throughout the website. https://share.cleanshot.com/2G1nvFhx 

That likely gives an amature, haphazard feel to the site. It also make means more work updating and maintain all these individual buttons. 

Create one single button component that can be used for all the buttons throughout the site. https://share.cleanshot.com/Kxy6wctx

Here's the new button component with all the different types and states we'll need to support long term. https://share.cleanshot.com/9YN8q9tL

Some of these states we maybe don't need to support now. At the very least we need these states.  https://share.cleanshot.com/79mjrsqW We can add the others later with another ticket.  

Here are all Figma prototype do get the exact specifications including colors, text and sizing. https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=15%3A344&mode=design&t=ZuIoRsDOGEK453Kk-1

**Comment by BayLadyCoder** [comment]
Hi, there! I'd like to work on this issue if no one is working on it.

**Comment by nlebovits** [comment]
> Hi, there! I'd like to work on this issue if no one is working on it.

Assigned! Thanks :)

**Comment by bacitracin** [comment]
Hey @BayLadyCoder ! Just an a11y request before you get started - if you end up creating a whole new button component from scratch, please use an actual <button> tag. 

If you end up staying with NextUi's Button component (perfectly fine, esp since we use a lot of their styling/props) please use `onPress` instead of `onClick` because onPress will cover both mouse & keyboard use and onClick only works w/mouse. 

Also when you create the disabled state, don't actually make the button disabled by passing the disabled attribute, instead use `aria-disabled`, apply disabled styling, and don't trigger the onClick. More info: https://css-tricks.com/making-disabled-buttons-more-inclusive/ 

Ok I know that's a lot, so if you have any questions feel free to Slack me!

**Comment by BayLadyCoder** [comment]
Makes sense, got it. Thanks for the info and the explanations, @bacitracin.

**Comment by BayLadyCoder** [comment]
@Moylena I'm still working on it. Probably need a couple more days to finish.

**Comment by marvieqa** [comment]
Hi 👋  @BayLadyCoder - linking to a Slack thread relating to this, in case you missed it! Cheers!

https://codeforphilly.slack.com/archives/C05H9QBMP96/p1710162484985779?thread_ts=1709753680.575579&cid=C05H9QBMP96

**Comment by Amberroseweeks** [comment]
@BayLadyCoder just tagging you to let you know that in Safari the buttons with icons and icon buttons had a unusual behavior they were jumping up and down on hover. Not sure if your work here will get rid of that, but in the meantime I added a quick fix, maybe we should include this within all buttons that have an icon just in case? https://github.com/CodeForPhilly/vacant-lots-proj/issues/422

**Comment by Moylena** [comment]
@JosephAni  this should be the conflicting ticket I should close since you are working on the nav, correct? CC @brandonfcohen1  @nlebovits  @thansidwell

**Comment by BayLadyCoder** [comment]
@Moylena No, we just agreed that I won't touch the nav since @JosephAni is rewriting it, but this ticket is updating all other buttons in the app.
