### ISSUE TITLE
Styling: Adjust table column width

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#305]
The first table column is so narrow it's causing a lot of text wrapping to the next line. 

Widen that column so it doesn't wrap. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/6c0138c0-9ec0-4eec-928d-6d493ed2977e)

**Comment by ajtw7** [comment]
@thansidwell, This behavior is due to the class that is currently being used for the `<th>` tag (table header).
I changed the class from `3/12` to `4/12`.
I haven't done the same for the table below, starting with **_Owner_**. 
If you're comfortable with these current changes, I'll make them consistent for the entire table and open a PR.


![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/63467369/f842083d-2524-4657-a3ce-4cf54ec6b113)



![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/63467369/4a0e880d-69b7-4339-a0e4-9e8a2caa9b4f)

**Comment by nlebovits** [comment]
> @nlebovits I'm looking into this.

assigned! thanks :)

**Comment by thansidwell** [comment]
Looking at this preview it all looks great too me!

(https://vercel.live/open-feedback/vacant-lots-proj-git-fork-ajtw7-a-87f418-clean-and-green-philly.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/4f5b2380-864a-4931-91d8-4d780f07db74)

**Comment by paulhchoi** [comment]
We can close this issue as its already been completed and merged with https://github.com/CodeForPhilly/vacant-lots-proj/pull/367
