### ISSUE TITLE
A11y: Improve pagination aria-labels for easy understanding

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/vacant-lots-proj#320]
## Describe

The pagination buttons are labeled as `<aria-label="pagination item x active">`. We can update it to describe the actual button action, or just simply say the page number. The "active" part is not necessary anymore if we are using `<aria-current="true">`.

## Recommendation

- [ ] update previous page button to `<aria-label="go to previous page">`
- [ ] update next page button to `<aria-label="go to next page">`
- [ ] update page number buttons to `<aria-label="go to page 1">`
- [ ] update forward jump button `...` to `<aria-label="jump to 5 pages forward>`
- [ ] update backward jump button `...` to `<aria-label="jump to 5 pages backwards>`

Relates to: #319

**Comment by itskarelleh** [comment]
Hello! I want to be assigned this issue, please.

**Comment by nlebovits** [comment]
Sure! Just assigned it to you @itskarelleh

**Comment by bacitracin** [comment]
@itskarelleh Hey! How's it going with this one? Let me know if you want to pair, I'm new to NextUI but hopefully everything can be accomplished with`getItemAriaLabel`

**Comment by itskarelleh** [comment]
Hi all,

Just wanted to let you know that I didn't abandon this issue. I'm working on it and will have it submitted tonight

**Comment by bacitracin** [comment]
> Hi all,
> 
> Just wanted to let you know that I didn't abandon this issue. I'm working on it and will have it submitted tonight

No worries, there isn't a rush. Take your time!

**Comment by marvieqa** [comment]
hi @itskarelleh ! Any updates on this ticket?

**Comment by Moylena** [comment]
@itskarelleh Hey there - if there hasn't been any movement on this, no worries! We're just going to pull you off the assignment for now. I'll complete the action tomorrow at 7 pm ET during our weekly call.

**Comment by Amberroseweeks** [comment]
I just noticed the iteration tags, if this issue is now available can I take this on? Thank you!

**Comment by Amberroseweeks** [comment]
Update: I have the aria labels applied to the all buttons except for the ellipse, because there are two of the same items I can't seem to target the one that jumps previous separately from the one that jumps forward. I also checked in with @thansidwell to confirm the design, I don't see pagination in the Figma currently. 

@bacitracin or @paulhchoi do you have any suggestions or insight on how I could target the ellipses or the dot button separately to apply a unique aria label there? The page item, next item and previous items all have unique values but the ellipses' value is "dots" (PaginationItemType.DOTS)


` const getItemAriaLabel = (page?: string | number | undefined): string => {
    if (typeof page === "number") {
      return `go to page  ${page}`;
    } else if (page === "prev") {
      return "go to previous page";
    } else if (page === "next") {
      return "go to next page";
    } else if (page === "dots") { 
      return "jump 5 pages"; // struggling on a way to identify whether the button is jumping forward or background to apply appropriate label
    }
    return ""; // Default label
  };`

**Comment by paulhchoi** [comment]
@Amberroseweeks A possible solution may be to query for all of the `<li>`'s under the `<nav role="pagination" />`, and run some logic to determine which direction its going to jump based on the values that come before/after it?

For example, you could run `const paginationElements = document.querySelectorAll('nav[aria-label="pagination"] ul li[role="button"]');`, and then check if the `<li>` element before the ellipsis is `page 1`, and if so, you can assume its going to jump to forward, and if not, you can assume its going to jump you backward. Tho a more robust solution may be to raise an issue with `@nextui-org/react` and [fix their code directly](https://github.com/nextui-org/nextui/blob/main/packages/components/pagination/src/use-pagination.ts#L344-L365) lol.

Hope this helps!

**Comment by bacitracin** [comment]
@Amberroseweeks I think we should probably remove the ellipses because even as a sighted person I am having a hard time following how many pages forward/backwards I'm going and why are these dots appearing and moving all around... I think if you set the `dotsJump` prop to 0 it might remove the effect?

I wouldn't lose too much sleep over this implementation, since we also have another ticket to rewrite the pagination.

**Comment by Amberroseweeks** [comment]
Thank you so much for responding @paulhchoi and @bacitracin ! I like the suggestion of removing the ellipses and @thansidwell is working on a pagination design update as well.
