### ISSUE TITLE
Multiple Page Titles Tags on Interior pages

### ISSUE THREAD

**Issue by Amberroseweeks** [CodeForPhilly/vacant-lots-proj#421]
**Describe the bug**
The interior pages of the website have multiple page titles. This is confusing for accessibility reasons and probably not very good for SEO. I added the fix for unique page titles, but adding in the <title> tag with the title is creating a new issue.

**To Reproduce**
1. Inspect an interior page such as Get Access, view the < head >
2. See that there will be three < title > tags

**Expected behavior**
Only one unique title tag per page.

**Screenshots**
<img width="353" alt="Screen Shot 2024-03-14 at 9 36 42 AM" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/61482332/fb1d5980-f3b9-4766-9b9c-f8312528ede4">

**Potential Fix**
I avoided using the Next Metadata API for this initially because our page components are not server components and next metadata only works on server components. (reference: https://stackoverflow.com/questions/76445050/not-able-to-change-the-title-with-metadata-when-using-use-client-in-next-js) So I believe a good fix could be converting the page.tsx to a server component, moving the interactive elements to a new component then importing those elements while adding the metadata information in each specific page.tsx file. This is a good tutorial: https://nextjs.org/learn/dashboard-app/adding-metadata

I am not sure if there are any implications to making this change though. I tested it out on a branch and it's working so far. 
<img width="406" alt="Screen Shot 2024-03-14 at 9 40 30 AM" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/61482332/52689654-a4fe-4da4-a561-940a6e15b93f">

**Comment by Amberroseweeks** [comment]
@paulhchoi tagging you here just in case you can provide some guidance, do you have a better solution for removing multiple page titles? Refactoring the page.tsx file could be time consuming and I can go ahead and do it but I wonder if there is a better way? Thank you for any insight you can share

**Comment by paulhchoi** [comment]
@Amberroseweeks this was actually something I had my eye on as well — you're on the right track to utilize next's Metadata API, but instead of refactoring the `page.tsx`, we can simply create a `layout.tsx` to wrap all of the pages at the root of the `app` directory to apply a 'base' metadata export in there, and then also add page-level layouts inside of the each page's folders (eg: `app/about/layout.tsx`, etc), and export the per-page metadata in there.

[This routing doc on nested layouts](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#nesting-layouts) and the [ordering/merging/inhereting](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#metadata) section of the metadata api doc should be a good place to start.

**Comment by paulhchoi** [comment]
@Amberroseweeks I actually already had a local branch to refactor some of the usages of layouts and pages, I can take this on if you hadn't started work on this already?

**Comment by Amberroseweeks** [comment]
@paulhchoi my availability is pretty limited during the day so if you can take this on that would be great! The main thing I am hoping to incorporate is unique page titles for each page. I also noticed some pages will be removed in the new design such as Methodology for example.

**Comment by paulhchoi** [comment]
this can be moved to `in review`
