### ISSUE TITLE
Content + Styling: Create content cards for "Transform a Property" - Green

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#430]
Create new GREEN content + image cards under the headers:

Basic interventions
Advanced interventions

This ticket does NOT include the BLUE content cards

Note headers within the cards are final, however you can greek the remaining content that is not fully baked yet. 

See Figma files for hex code and keystrokes

https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-31488&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

**Comment by bacitracin** [comment]
A11y note: Seems like the content of the cards is in flux, but when we do have the copy, let's make sure to avoid vague link titles like "Learn More" - https://www.plousia.com/blog/learn-more-or-read-more-links-bad-news-accessibility

**Comment by Amberroseweeks** [comment]
I'd like to assign myself this task if no one is working on this yet. Can we consider using a <li> element and making the whole card clickable like this example? https://inclusive-components.design/cards/

**Comment by bacitracin** [comment]
> I'd like to assign myself this task if no one is working on this yet. Can we consider using a < li > element and making the whole card clickable like this example? https://inclusive-components.design/cards/

Love Heydon Pickering! @marvieqa might have some opinions on the cards.

I'll assign the ticket to you, but it looks like @Moylena added the blocked tag so check to see what's up with that first.

**Comment by Moylena** [comment]
@Amberroseweeks  @bacitracin  @marvieqa  I had the status as blocked because the Figma design doesn't have all the final copy!

**Comment by Moylena** [comment]
@thansidwell  will drop layout updates!

**Comment by thansidwell** [comment]
@Moylena @Amberroseweeks @bacitracin @marvieqa  I finished writing the content for the cards! Check out the [Figma page](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592%3A31488&mode=design&t=8ENXrNjGR8ZzXMuG-1)

I think the links are best looking like text links with arrows suggesting you'll go to another website and it opens another tab. The number of links vary. Some have no links, most 1, some 2 and one 3. Because of that I don't think making the whole card makes sense. Plus the links allow you to inform what website you are taking them to.

<img width="1114" alt="Screenshot 2024-04-09 at 11 04 29 PM" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/0249080b-72c0-41c6-a533-182e0d88bee7">

**Comment by Amberroseweeks** [comment]
@thansidwell I am working on this today, my only concern is the blue link color against green-200, for normal size text, 16px this is throwing a contrast error https://webaim.org/resources/contrastchecker/?fcolor=0070F0&bcolor=E9FFE5

Can we consider using a lighter color for cards or maybe an alternate link color? 

cc @marvieqa and @bacitracin

**Comment by thansidwell** [comment]
Good catch! We could just darken that blue color variable. #006DEE would pass. https://webaim.org/resources/contrastchecker/?fcolor=0070F0&bcolor=E9FFE5

**Comment by nlebovits** [comment]
closed by #514
