### ISSUE TITLE
Map: Enhancement needed when pulling up properties from Search

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/vacant-lots-proj#486]
## Description

When a property is pulled up via the Search field, we don't show any indication where the property is in the map. We should point the property in the map when searched. 

- For actionable properties
- For unavailable/not actionable properties

## Additional Info

We should identify the user flow, taking in to consideration how the map works right now as a mouse user.  For example:
- When user enters an exact address of an **_available property_** and selects it:
  - Do automatically select the property on the map and display the pop-up, then show the property details on the right panel?
- When user enters an address of **_not available_** property:
  -  What does this look like?

**Comment by marvieqa** [comment]
Note: We can update this ticket when we get a design.

**Comment by thansidwell** [comment]
@marvieqa I would suggest this behavior. 

- When a user searches for a properity that turns out to be **vacant** -- [Figma Prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=4304%3A35573&mode=design&t=Yw7lsREV4lSzMQxH-1)

  - The map shifts to the property
  - A tooltip marks the property
  - The property details are displayed on the right panel.

<img width="1057" alt="CleanShot 2024-04-02 at 23 58 40@2x" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/bd59bf8d-b1cb-4ed0-80d3-b34c2c0df8d6">

- When a user searches for a properity that turns out to be **not vacant** -- [Figma Prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=4304%3A35330&mode=design&t=Yw7lsREV4lSzMQxH-1)
  - The map shifts to the property
  - A tooltip marks the property
  - The right panel doesn't change, but stays the list
    
<img width="1058" alt="CleanShot 2024-04-02 at 23 58 33@2x" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/0a441cd0-a047-426a-8914-73f7d43ba44a">

**Comment by jgrimes86** [comment]
Hello @Moylena, I think I can address this one.

**Comment by nlebovits** [comment]
closed by #532
